eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 9090
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
    sleuth:
        reactor:
            instrumentation-type: decorate_on_each
    zipkin:
        base-url: http://localhost:9411
