address:
    service:
        path: /api/address
        url: http://localhost:8082
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
# If you face error like "java.net.UnknownHostException: failed to resolve...."
#   instance
#       hostname: localhost

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health
    health:
        circuitbreakers:
            enabled: true
resilience4j:
    circuitbreaker:
        instances:
            addressService:
                allow-health-indicator-to-fail: true
                automatic-transition-from-open-to-half-open-enabled: true
                failure-rate-threshold: 50
                permitted-number-of-calls-in-half-open-state: 5
                register-health-indicator: true
                sliding-window-size: 10
                wait-duration-in-open-state: 30000
server:
    port: 8080
spring:
    application:
        name: student-service
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/university
        username: postgres
    zipkin:
        base-url: http://localhost:9411
